# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']

MACHINES = {
  :otuslinux => {
    :box_name => "centos/7",
    :ip_addr => '192.168.11.101',
    :disks => {
      :sata1 => {
        :dfile => home+'/module1/HWdisksub/sata1.vdi',
        :size => 250,
        :port => 1
      },
      :sata2 => {
        :dfile => home+'/module1/HWdisksub/sata2.vdi',
        :size => 250, # Megabytes
        :port => 2
      },
      :sata3 => {
        :dfile => home+'/module1/HWdisksub/sata3.vdi',
        :size => 250,
        :port => 3
      },
      :sata4 => {
        :dfile => home+'/module1/HWdisksub/sata4.vdi',
        :size => 250, # Megabytes
        :port => 4
      },
      :sata5 => {
        :dfile => home+'/module1/HWdisksub/sata5.vdi',
        :size => 250,
        :port =>5
      },
      :sata6 => {
        :dfile => home+'/module1/HWdisksub/sata6.vdi',
        :size => 250,
        :port => 6
      },
      
    }
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

      box.vm.box = boxconfig[:box_name]

      box.vm.host_name = boxname.to_s

      #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset
      box.vm.network "private_network", ip: boxconfig[:ip_addr]

      box.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
        needsController = false
        boxconfig[:disks].each do |dname, dconf|
          unless File.exist?(dconf[:dfile])
            vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
            needsController =  true
            end
          end
            if needsController == true
              vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
              boxconfig[:disks].each do |dname, dconf|
                vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                end
              end
            end

      box.vm.provision "shell", path: "script_arrya.sh"

    end
  end
end

